apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb-scada
    url: timescaledb:5432
    user: ${POSTGRES_USER:-scada}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-scada}
    jsonData:
      database: ${POSTGRES_DB:-scada_db}
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600   # PostgreSQL 16
      timescaledb: true
    isDefault: true
    editable: false
